name: Scheduled Unit Tests

on:
  schedule:
    - cron:  '*/30 5,17 * * *'

jobs:
  # 1 Run unit tests
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: set up JDK 1.8
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create credential-free local properties
        run: touch local.properties

      - name: Clean
        run: ./gradlew clean

      - name: Unit tests
        run: ./gradlew test
